<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>irb120_description</name>
  <version>1.0.0</version>
  <description>
    Gemelo digital cinematico del manipulador ABB IRB 120 (6 GDL).
    Descripcion URDF generada programaticamente a partir de la tabla
    Denavit-Hartenberg y validada contra la cinematica directa analitica.
    Grupo VEVAS.
  </description>
  <maintainer email="florencia.frigerio@ucb.edu.bo">florencia</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>tf2_ros</exec_depend>

  <test_depend>ament_lint_auto</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
