export const ABB_SOURCE='https://library.e.abb.com/public/7aa0711a20fa41c49a8fdf3bbc3d5bb0/IRB120-Rev.J-ROBO149EN_D.pdf';
export const parts=[
 {id:'base',num:'00',name:'Base y conexiones',short:'Base',nodes:[6,7,8,9,10,11,12,13,14],subtitle:'Soporte fijo del manipulador',body:'Fija el robot a su superficie de montaje y transmite las cargas a la estructura de soporte. En la parte posterior se observan conexiones y elementos auxiliares del modelo.',specs:[['Base del robot','180 × 180 mm'],['Montaje de catálogo','Cualquier ángulo'],['Protección del robot','IP30']],note:'El tamaño de base es un dato de catálogo. Los conectores del modelo no tienen identificación eléctrica verificada.',offset:[-.2,0,-.14]},
 {id:'j1',num:'J1',name:'Cuerpo giratorio',short:'Cuerpo · J1',nodes:[16],subtitle:'Eje 1 · rotación de la base',body:'Orienta el conjunto del brazo alrededor de la base. Es el primer eslabón móvil de la cadena y permite dirigirse a distintas zonas alrededor del robot.',range:[-165,165],speed:250,motion:'Rotación de base',note:'Se resalta el conjunto asociado a J1. La postura del archivo es una pose fija; el visor no representa el ángulo articular actual.',offset:[0,.07,-.07]},
 {id:'j2',num:'J2',name:'Brazo inferior',short:'Brazo · J2',nodes:[18,19,20],subtitle:'Eje 2 · movimiento del brazo',body:'Une el cuerpo giratorio con el conjunto del codo. Su giro cambia la elevación del brazo y contribuye a acercar o alejar la herramienta de la base.',range:[-110,110],speed:250,motion:'Giro del brazo',note:'El hombro es una articulación rotativa. El motor y el reductor internos no están identificados por referencia en este modelo.',offset:[-.18,.18,-.02]},
 {id:'j3',num:'J3',name:'Codo y soporte',short:'Codo · J3',nodes:[22,23],subtitle:'Eje 3 · movimiento del brazo',body:'Articula el brazo con el tramo que conduce a la muñeca. Su movimiento, combinado con J1 y J2, permite modificar la posición de la herramienta.',range:[-110,70],speed:250,motion:'Giro del codo',note:'El recorrido es asimétrico: −110° a +70° en la ficha ABB consultada. No confundir estos límites con la orientación de la geometría descargada.',offset:[.02,.3,-.02]},
 {id:'j4',num:'J4',name:'Antebrazo',short:'Antebrazo · J4',nodes:[25,26,27,28,29,30],subtitle:'Eje 4 · rotación de muñeca',body:'Conduce hacia la muñeca y permite girar el conjunto distal alrededor de su eje longitudinal. Inicia la orientación fina de la herramienta.',range:[-160,160],speed:320,motion:'Rotación de muñeca',note:'Las tapas y detalles visibles se seleccionan como un conjunto funcional. No equivalen a una lista de repuestos del fabricante.',offset:[.18,.18,.08]},
 {id:'j5',num:'J5',name:'Muñeca',short:'Muñeca · J5',nodes:[32,33],subtitle:'Eje 5 · flexión de muñeca',body:'Inclina el extremo del brazo. Este movimiento permite cambiar la dirección de aproximación de una herramienta, por ejemplo para orientar una pinza hacia una superficie.',range:[-120,120],speed:320,motion:'Flexión de muñeca',note:'La asociación del conjunto a J5 es didáctica. No se dibujan ejes geométricos calibrados ni se calcula una trayectoria.',offset:[.24,.06,.14]},
 {id:'j6',num:'J6',name:'Brida de herramienta',short:'Brida · J6',nodes:[35,36],subtitle:'Eje 6 · giro de herramienta',body:'Es la interfaz final del robot con el adaptador de la herramienta. El sexto eje permite girar la herramienta sobre su propio eje para orientar el agarre.',range:[-400,400],speed:420,motion:'Giro de herramienta',note:'±400° es el rango predeterminado de catálogo. No se muestran ampliaciones configurables. La pinza requiere una interfaz mecánica compatible.',offset:[.27,-.035,.18]},
 {id:'gripper',num:'EF',name:'Pinza y mordazas',short:'Pinza',nodes:[42,44,46],subtitle:'Efector final representado',body:'El modelo incluye una pinza con dos mordazas que sujetan la pieza. En el proyecto se propone una pinza neumática de doble efecto, accionada mediante electroválvulas.',specs:[['Representación','Dos mordazas'],['Referencia comercial','No identificada'],['Fuerza y carrera','Por seleccionar']],note:'El aspecto de esta geometría no confirma el mecanismo interno. La pinza del proyecto debe seleccionarse según pieza, agarre y carga admisible.',model:true,offset:[.29,-.1,.23]},
 {id:'piece',num:'P',name:'Pieza de ejemplo',short:'Pieza',nodes:[38],subtitle:'Objeto de manipulación',body:'El bloque permite explicar el objetivo del sistema: localizar una pieza, sujetarla y trasladarla. Es un objeto de la escena, no un componente del manipulador ABB.',specs:[['Forma representada','Prismática'],['Material','No documentado'],['Masa real','No documentada']],note:'La escena muestra una situación de agarre ilustrativa. No demuestra detección por cámara, fuerzas de contacto ni un ciclo de paletizado.',model:true,offset:[.28,-.025,.35]}
];
export const bom=[
 ['ABB IRB 120','1','Manipulador de 6 ejes; alcance de 580 mm y carga nominal de 3 kg.','Definido en la guía'],
 ['Controlador ABB IRC5','1','Control del robot y comunicación Ethernet TCP/IP.','Definido en la guía'],
 ['Pinza neumática','1','Doble efecto; fuerza, carrera y geometría según la pieza.','Referencia por seleccionar'],
 ['Adaptador de herramienta','1','Une la pinza con la brida. Diseñar interfaz y comprobar carga.','Diseño por definir'],
 ['Electroválvula','1*','Acciona la pinza; mando de 24 V según la guía.','Circuito por dimensionar'],
 ['Alimentación neumática','1 conjunto','Suministro, regulación, filtrado y tuberías según la pinza.','Propuesta de integración'],
 ['Cámara USB cenital','1','HD/Full HD; enfoque manual fijo; montaje a 80 cm según la guía.','Modelo por seleccionar'],
 ['Computadora','1','Procesamiento de imagen, cinemática y comunicación con el controlador.','Prestaciones por definir'],
 ['Conexión Ethernet','1 enlace','Comunicación entre computadora y controlador.','Topología por definir'],
 ['Mesa y soporte de cámara','1 conjunto','Superficie de piezas y montaje estable del sensor.','Diseño por definir'],
 ['Zona de descarga / palet','1 conjunto','Organiza las piezas clasificadas.','Diseño por definir'],
 ['Vernier digital','1','Medición del error físico; precisión ±0,02 mm indicada en la guía.','Definido en la guía']
];
